// <auto-generated />
using System;
using DoAnWEBDEMO.ApplicationDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnWEBDEMO.Migrations
{
    [DbContext(typeof(ApplicationDb))]
    partial class ApplicationDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnWEBDEMO.Models.BaiViet", b =>
                {
                    b.Property<int>("MaBV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBV"));

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBV");

                    b.ToTable("BaiViet");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.ChiTietBinhLuan", b =>
                {
                    b.Property<int>("MA_KH")
                        .HasColumnType("int");

                    b.Property<int>("MA_SP")
                        .HasColumnType("int");

                    b.Property<int>("Id_BinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_BinhLuan"));

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NGAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOI_DUNG")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SO_SAO")
                        .HasColumnType("int");

                    b.HasKey("MA_KH", "MA_SP", "Id_BinhLuan");

                    b.HasIndex("MA_SP");

                    b.ToTable("ChiTietBinhLuan");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MA_DH")
                        .HasColumnType("int");

                    b.Property<int>("MA_SP")
                        .HasColumnType("int");

                    b.Property<int>("MA_MAU")
                        .HasColumnType("int");

                    b.Property<int>("SOLUONG")
                        .HasColumnType("int");

                    b.Property<decimal>("TONGTIENTUNGSANPHAM")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MA_DH", "MA_SP", "MA_MAU");

                    b.HasIndex("MA_MAU");

                    b.HasIndex("MA_SP");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<int>("MaMau")
                        .HasColumnType("int");

                    b.Property<int?>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("MaKH", "MaSP", "MaMau");

                    b.HasIndex("MaMau");

                    b.HasIndex("MaSP");

                    b.ToTable("ChiTietGioHang");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.DanhMuc", b =>
                {
                    b.Property<int>("Ma_DM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ma_DM"));

                    b.Property<string>("TenDM")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Trang_Thai")
                        .HasColumnType("int");

                    b.HasKey("Ma_DM");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.DonHang", b =>
                {
                    b.Property<int>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDH"));

                    b.Property<string>("DiaChiNhanHang")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int?>("MaNVXL")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDatHang")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("TongTienDonHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDH");

                    b.HasIndex("MaKH");

                    b.HasIndex("MaNVXL");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoKH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MATKHAU")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TENNGUOIDUNG")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKH");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.KhuyenMai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MucGiamGia")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("SanPhamKhuyenMaiId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SanPhamKhuyenMaiId");

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.LienHe", b =>
                {
                    b.Property<int>("MA_LH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MA_LH"));

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HO_TEN")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MA_NVXL")
                        .HasColumnType("int");

                    b.Property<string>("NOI_DUNG")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime>("THOI_GIAN_GUI")
                        .HasColumnType("datetime2");

                    b.Property<int>("TRANG_THAI")
                        .HasColumnType("int");

                    b.HasKey("MA_LH");

                    b.HasIndex("MA_NVXL");

                    b.ToTable("LienHe");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.MauSac", b =>
                {
                    b.Property<int>("ID_MauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_MauSac"));

                    b.Property<string>("HinhAnhSP_MauSac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaSP")
                        .HasColumnType("int");

                    b.Property<int>("SoLuongTon_MS")
                        .HasColumnType("int");

                    b.Property<string>("TenMauSac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID_MauSac");

                    b.HasIndex("MaSP");

                    b.ToTable("MauSac");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.NhaCungCap", b =>
                {
                    b.Property<int>("MaNCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNCC"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNCC")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNCC");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.NhanVien", b =>
                {
                    b.Property<int>("MA_NV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MA_NV"));

                    b.Property<string>("EMAIL")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MATKHAU")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TENDANGNHAP")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TENNV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TRANGTHAI")
                        .HasColumnType("int");

                    b.HasKey("MA_NV");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.SanPham", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"));

                    b.Property<string>("Bo_Nho_Trong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CameraSau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Camera_Truoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Chipset")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Dung_Luong_Ram")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HeDieuHanh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HinhAnhSP")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KichThuoc_ManHinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("LuotXem")
                        .HasColumnType("int");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaNCC")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayRaMat")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SlideShow")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TEN_SP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TGianBaoHanh")
                        .HasColumnType("int");

                    b.Property<string>("TanSoQuet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSP");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaNCC");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.SanPhamYeuThich", b =>
                {
                    b.Property<int>("KhachHangId")
                        .HasColumnType("int");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.HasKey("KhachHangId", "SanPhamId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("SanPhamYeuThich");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.ChiTietBinhLuan", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.KhachHang", "KhachHang")
                        .WithMany("ChiTietBinhLuans")
                        .HasForeignKey("MA_KH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWEBDEMO.Models.SanPham", "SanPham")
                        .WithMany("ChiTietBinhLuans")
                        .HasForeignKey("MA_SP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MA_DH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWEBDEMO.Models.MauSac", "MauSac")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MA_MAU")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnWEBDEMO.Models.SanPham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MA_SP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.KhachHang", "KhachHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWEBDEMO.Models.MauSac", "MauSac")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaMau")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoAnWEBDEMO.Models.SanPham", "SanPham")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("MauSac");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.DonHang", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.KhachHang", "KhachHang")
                        .WithMany("DonHang")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWEBDEMO.Models.NhanVien", "NhanVien")
                        .WithMany("DonHang")
                        .HasForeignKey("MaNVXL")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("KhachHang");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.KhuyenMai", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.SanPham", "SanPham")
                        .WithMany("KhuyenMais")
                        .HasForeignKey("SanPhamKhuyenMaiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.LienHe", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.NhanVien", "NhanVien")
                        .WithMany("LienHe")
                        .HasForeignKey("MA_NVXL")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.MauSac", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.SanPham", "SanPham")
                        .WithMany("MauSacs")
                        .HasForeignKey("MaSP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.SanPham", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.DanhMuc", "DanhMuc")
                        .WithMany("SanPham")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWEBDEMO.Models.NhaCungCap", "NhaCungCap")
                        .WithMany("SanPham")
                        .HasForeignKey("MaNCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DanhMuc");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.SanPhamYeuThich", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.KhachHang", "KhachHang")
                        .WithMany("SanPhamYeuThichs")
                        .HasForeignKey("KhachHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWEBDEMO.Models.SanPham", "SanPham")
                        .WithMany("SanPhamYeuThichs")
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.DanhMuc", b =>
                {
                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.KhachHang", b =>
                {
                    b.Navigation("ChiTietBinhLuans");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("DonHang");

                    b.Navigation("SanPhamYeuThichs");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.MauSac", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.NhaCungCap", b =>
                {
                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.NhanVien", b =>
                {
                    b.Navigation("DonHang");

                    b.Navigation("LienHe");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietBinhLuans");

                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("KhuyenMais");

                    b.Navigation("MauSacs");

                    b.Navigation("SanPhamYeuThichs");
                });
#pragma warning restore 612, 618
        }
    }
}
