// <auto-generated />
using System;
using DoAnWEBDEMO.Access;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnWEBDEMO.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnWEBDEMO.Models.CHI_TIET_BINH_LUAN", b =>
                {
                    b.Property<int>("MA_KH")
                        .HasColumnType("int");

                    b.Property<int>("MA_SP")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("NGAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("NOI_DUNG")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SO_SAO")
                        .HasColumnType("int");

                    b.HasKey("MA_KH", "MA_SP");

                    b.HasIndex("MA_SP");

                    b.ToTable("CHI_TIET_BINH_LUANs");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.CHI_TIET_DON_HANG", b =>
                {
                    b.Property<int>("MA_DH")
                        .HasColumnType("int");

                    b.Property<int>("MA_SP")
                        .HasColumnType("int");

                    b.Property<int>("SOLUONG")
                        .HasColumnType("int");

                    b.Property<decimal>("TONGTIENTUNGSANPHAM")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MA_DH", "MA_SP");

                    b.HasIndex("MA_SP");

                    b.ToTable("CHI_TIET_DON_HANGs");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.DON_HANG", b =>
                {
                    b.Property<int>("MaDH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDH"));

                    b.Property<string>("DiaChiNhanHang")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("MaKH")
                        .HasColumnType("int");

                    b.Property<int>("MaNV")
                        .HasColumnType("int");

                    b.Property<string>("NgayDatHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("TongTienDonHang")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaDH");

                    b.ToTable("DON_HANGs");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.KHACH_HANG", b =>
                {
                    b.Property<int>("MaKH")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKH"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoKH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenKH")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKH");

                    b.ToTable("kHACH_HANGs");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.San_Pham", b =>
                {
                    b.Property<int>("MaSP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSP"));

                    b.Property<string>("HinhAnhSP")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaNCC")
                        .HasColumnType("int");

                    b.Property<string>("MauSP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TGianBaoHanh")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaSP");

                    b.ToTable("San_Phams");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.CHI_TIET_BINH_LUAN", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.KHACH_HANG", "KhachHang")
                        .WithMany("ChiTietBinhLuans")
                        .HasForeignKey("MA_KH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWEBDEMO.Models.San_Pham", "SanPham")
                        .WithMany("ChiTietBinhLuans")
                        .HasForeignKey("MA_SP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.CHI_TIET_DON_HANG", b =>
                {
                    b.HasOne("DoAnWEBDEMO.Models.DON_HANG", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MA_DH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWEBDEMO.Models.San_Pham", "SanPham")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MA_SP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.DON_HANG", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.KHACH_HANG", b =>
                {
                    b.Navigation("ChiTietBinhLuans");
                });

            modelBuilder.Entity("DoAnWEBDEMO.Models.San_Pham", b =>
                {
                    b.Navigation("ChiTietBinhLuans");

                    b.Navigation("ChiTietDonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
